### PR TITLE
Add uninstall.php

### PR DESCRIPTION
**Pull request by lukecav**
Add uninstall.php which will remove any options added by MainWP Child plugin on install and flush cache.

### CODE REVIEW

**Comment by Filoz** [comment]
IMHO, it should ask if you really want to remove options or not.

**Comment by dennisdornon** [comment]
We wouldn't want an uninstall option without @filoz suggestion for an option to remove them or not for numerous reasons including an accidental deactivation or deactivation for testing causing issues with reconnecting to the Dashboard.

**Comment by bogdan-mainwp** [comment]
There is also a way to clean MainWP Child data from database by running this MySQL command:

`DELETE FROM `wp_options` where option_name like '%mainwp_%'`

As described in this [help document](https://mainwp.com/help/docs/delete-mainwp-related-content-from-a-child-site-database/).

**Comment by bogdan-mainwp** [comment]
Since this is not something that we want in MainWP Child so there is no data loss caused by accidentaly plugin reactivation and removal, we will  skip this pull request.

**Pull request closed without merging**
